### ISSUE TITLE
Make the idfields parameter optionnal

### ISSUE THREAD

**Issue by djhi** [marmelab/coPostgresQuery#6]
For all select\* functions and `crud`, add a default for the `idfields` option: `'id']`

**Comment by alexisjanvier** [comment]
@djhi @ThieryMichel It's not seem so easy, because this functions haven't a single object as parameter, and `idfields` is not the last one. So we can't leave it empty to get a potential default parameter, isn't it?

**Comment by ThieryMichel** [comment]
done
